# -*- coding: utf-8 -*-
"""analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PdBNwTRAY_DvlDRvGc1zspn_EN6TtDkw
"""

import pandas as pd

df = pd.read_csv("Iris.csv")

print(df.head())
print(df.info())
print(df.describe())
print(df.isnull().sum())

